apiVersion: v1
kind: Service
metadata:
  name: memphis-cluster-external
  namespace: memphis
spec:
  ports:
  - name: memphis-cp
    port: 9000
    targetPort: 9000
  - name: memphis-cp-tcp
    port: 6666
    targetPort: 6666  
  selector:
    app.kubernetes.io/instance: memphis
    app.kubernetes.io/name: memphis
  type: LoadBalancer
